import type { LeadStatus } from "@prisma/client";

export const PIPELINE_STATUSES: LeadStatus[] = [
  "NEW",
  "REVIEWED",
  "CONTACTED",
  "RESPONDED",
  "MEETING",
  "PROPOSAL",
  "NEGOTIATION",
  "WON",
  "LOST",
];

export const STATUS_LABELS: Record<LeadStatus, string> = {
  NEW: "New",
  REVIEWED: "Reviewed",
  CONTACTED: "Contacted",
  RESPONDED: "Responded",
  MEETING: "Meeting",
  PROPOSAL: "Proposal",
  NEGOTIATION: "Negotiation",
  WON: "Won",
  LOST: "Lost",
  NOT_INTERESTED: "Not interested",
  FOLLOW_UP: "Follow-up",
};

export const DEFAULT_TAGS = [
  "HOT",
  "WEBSITE",
  "WEB_APP",
  "MOBILE_APP",
  "REDESIGN",
  "E_COMMERCE",
  "BOOKING",
  "REAL_ESTATE",
  "CLINIC",
  "RESTAURANT",
  "FASHION",
  "CHENNAI",
  "HIGH_VALUE",
] as const;

export const IMPORTABLE_FIELDS = [
  "businessName",
  "category",
  "industry",
  "description",
  "city",
  "state",
  "country",
  "address",
  "location",
  "googleMapsUrl",
  "website",
  "businessSize",
  "status",
  "leadScore",
  "scoreReason",
  "detectedProblem",
  "suggestedSolution",
  "solutionNeeded",
  "suggestedService",
  "suggestedPitch",
  "opportunityType",
  "businessOpportunity",
  "whyThisLead",
  "leadIntelCategory",
  "buyingIntent",
  "intentScore",
  "projectType",
  "postedAt",
  "postUrl",
  "postPlatform",
  "postAuthor",
  "postAuthorRole",
  "postTextSummary",
  "requirementSummary",
  "businessValue",
  "contactName",
  "contactRole",
  "phone",
  "whatsApp",
  "email",
  "linkedIn",
  "instagram",
  "facebook",
  "sourceType",
  "sourceUrl",
  "websiteStatus",
  "nextFollowUpAt",
] as const;
